apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-all-is-well-feb-dev

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: all-is-well-feb
  environment: dev
  tenant: opsera
  managed-by: opsera-cicd

images:
  - name: PLACEHOLDER_ECR_URI
    newName: PLACEHOLDER_ECR_URI
    newTag: latest
