apiVersion: v1
kind: Service
metadata:
  name: all-is-well-feb
  labels:
    app: all-is-well-feb
    environment: dev
    tenant: opsera
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: all-is-well-feb
    environment: dev
