apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opsera-all-is-well-dev
  namespace: argocd
  labels:
    tenant: opsera
    app: all-is-well
    environment: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/opsera-test-org/all-is-well.git
    targetRevision: main
    path: .opsera-all-is-well/k8s/overlays/dev
  destination:
    name: opsera-usw2-np
    namespace: opsera-all-is-well-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
