apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-all-is-well-dev

resources:
  - ../../base
  - namespace.yaml

labels:
  - includeSelectors: false
    pairs:
      environment: dev
      tenant: opsera

images:
  - name: PLACEHOLDER_ECR_URI
    newName: PLACEHOLDER_ECR_URI
    newTag: dev-latest

replicas:
  - name: all-is-well
    count: 2
